name: Continue Integration with parse data from Wiki

on: [push]

jobs:

  get-print-data:

    name: Test Get and Print Data
    runs-on: ubuntu-latest

    steps:
      - name: Update System Requirements
        run: sudo apt update

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          pip install --upgrade pip
          pip install poetry

      - name: Install Requirements
        run: |
          poetry export -f requirements.txt --with dev --output requirements.txt
          pip install -r requirements.txt

      - name: Lint style
        run: ruff check

      - name: Build Image
        run: docker compose -f docker-compose.ci.yaml build

      - name: Get Data
        run: docker compose -f docker-compose.ci.yaml up get_data

      - name: Print Data
        run: docker compose -f docker-compose.ci.yaml up print_data
